######################################################################
######################################################################
#     Sample information
######################################################################

# FASTQ files for each individual sample
samples:
  ANT1_S3: 
    - ANT1_S3_L001_R1_001.fastq.gz
    - ANT1_S3_L002_R1_001.fastq.gz
  BOY6_S9:
    - BOY6_S9_L001_R1_001.fastq.gz
    - BOY6_S9_L002_R1_001.fastq.gz
  CAT3_S1:
    - CAT3_S1_L001_R1_001.fastq.gz
    - CAT3_S1_L002_R1_001.fastq.gz

# input key for each individual sample
ids:
  ANT1_S3: CAT3_S1
  BOY6_S9: CAT3_S1

# combine samples which are replicates
combined:
  ANT1_BOY6:
    - ANT1_S3
    - BOY6_S9


######################################################################
######################################################################
#     Directory information
# 
# directories should to be relative to the Snakemake working directory 
# e.g. simply write as output/, no need to prefix with "./"
#
# an exception can be made for sampledir,
# as these (large) files might be somewhere else 
# in this case, use an absolute dir (e.g. /path/to/raw/FASTQ/)
#
# IMPORTANT: make sure directories end with a forward slash /
######################################################################

# location of raw fastq files
sampledir: data/samples/

# location for output files of Snakemake pipeline
outputdir: output/

# subdirectories within outputdir
# e.g. qc: qc/ will become outputdir/qc/
subdir:
  qc: qc/
  log: log/
  tmp: tmp/
  bam: bam/
  macs2: macs2/
  summary: summary/    # processed as subdir of macs2
  combined: combined/  # processed as subdir of macs2


######################################################################
######################################################################
#     Settings for packages
######################################################################

# reference genome 
refgenome: data/genome.fa
refchromsizes: data/genome.chrom-sizes

# settings for trimmomatic
# there should be a space after each line of settings
trimmomatic:
  settings:
    ILLUMINACLIP:/mnt/home1/miska/jlp76/programs/Trimmomatic-0.39/adapters/TruSeq3-SE.fa:2:30:10 
    ILLUMINACLIP:/mnt/home1/miska/jlp76/programs/Trimmomatic-0.39/adapters/TruSeq2-SE.fa:2:30:10 
    SLIDINGWINDOW:4:28 MINLEN:20

# settings for MACS2
# there should be a space after each line of settings
macs2:
  settings:
    --gsize 8.8e8 --extsize 147 --nomodel -q 0.01 -B --cutoff-analysis 

