samples:
  ANT1_S3: 
    - ANT1_S3_L001_R1_001.fastq.gz
    - ANT1_S3_L002_R1_001.fastq.gz
  BOY6_S9:
    - BOY6_S9_L001_R1_001.fastq.gz
    - BOY6_S9_L002_R1_001.fastq.gz
  CAT3_S1:
    - CAT3_S1_L001_R1_001.fastq.gz
    - CAT3_S1_L002_R1_001.fastq.gz

# specify the inputs
ids:
  ANT1_S3: CAT3_S1
  BOY6_S9: CAT3_S1

sampledir: data/samples/

outputdir: output/

subdir:
  qc: qc/
  log: log/
  tmp: tmp/
  bam: bam/
  macs2: macs2/

refgenome: data/genome.fa
refchromsizes: data/genome.chrom-sizes

# pls have a space after each line of settings
trimmomatic:
  bin: /mnt/home1/miska/jlp76/programs/Trimmomatic-0.39/trimmomatic-0.39.jar
  settings:
    ILLUMINACLIP:/mnt/home1/miska/jlp76/programs/Trimmomatic-0.39/adapters/TruSeq3-SE.fa:2:30:10 
    ILLUMINACLIP:/mnt/home1/miska/jlp76/programs/Trimmomatic-0.39/adapters/TruSeq2-SE.fa:2:30:10 
    SLIDINGWINDOW:4:28 MINLEN:20

igvtools:
  bin: /mnt/home1/miska/fxq20/home3/software/IGV_2.7.2/igvtools

# pls have a space after each line of settings
macs2:
  settings:
    --gsize 8.8e8 --extsize 147 --nomodel -q 0.01 -B --cutoff-analysis 
