samples:
  A: 
    - A_L001_R1_001.fastq.gz
    - A_L002_R1_001.fastq.gz
  B:
    - B_L001_R1_001.fastq.gz
    - B_L002_R1_001.fastq.gz
  C:
    - C_L001_R1_001.fastq.gz
    - C_L002_R1_001.fastq.gz

sampledir: data/samples/

outputdir: output/

subdir:
  qc: qc/
  log: log/
  tmp: tmp/
