samples:
  A: 
    - A_L001_R1_001.fastq.gz
    - A_L002_R1_001.fastq.gz
  B:
    - B_L001_R1_001.fastq.gz
    - B_L002_R1_001.fastq.gz
  C:
    - C_L001_R1_001.fastq.gz
    - C_L002_R1_001.fastq.gz

sampledir: data/samples/

outputdir: output/

subdir:
  qc: qc/
  log: log/
  tmp: tmp/

refgenome: data/genome.fa

# pls have a space after each line of settings
trimmomatic:
  bin: /mnt/home1/miska/jlp76/programs/Trimmomatic-0.39/trimmomatic-0.39.jar
  settings:
    ILLUMINACLIP:/mnt/home1/miska/jlp76/programs/Trimmomatic-0.39/adapters/TruSeq3-SE.fa:2:30:10 
    ILLUMINACLIP:/mnt/home1/miska/jlp76/programs/Trimmomatic-0.39/adapters/TruSeq2-SE.fa:2:30:10 
    SLIDINGWINDOW:4:28 MINLEN:20
