######################################################################
######################################################################
#     Sample information
######################################################################

# reference genome 
refgenome: data/genome.fa
refchromsizes: data/genome.chrom-sizes

# location of raw fastq files
sampledir: data/samples/

######################################################################
######################################################################
#     Settings for packages
######################################################################

# settings for trimmomatic
# there should be a space after each line of settings
trimmomatic:
  settings:
    ILLUMINACLIP:adapter/TruSeq3-SE.fa:2:30:10 
    ILLUMINACLIP:adapter/TruSeq2-SE.fa:2:30:10 
    SLIDINGWINDOW:4:28 MINLEN:20

# settings for MACS2
# there should be a space after each line of settings
macs2:
  settings:
    --gsize 8.8e8 --extsize 147 --nomodel -q 0.01 -B --cutoff-analysis 

